name: Deploy on PR Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Execute script on remote server
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: "churchlify-api.7thcolonnade.com"
        username: "solo"
        key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ8S85AfYDNZGnQIqSbdfUyHg9rl/2gsAGXd4CCKnMfM solo@blackswan"
        script: |
          cd /srv/appHome/nodeapps/churchlify-api/
          git pull origin main
          docker-compose -p sevenc up -d --build
